(*
   .......S.......
   ...............
   .......^.......
   ...............
   ......^.^......
   ...............
   .....^.^.^.....
   ...............
   ....^.^...^....
   ...............
   ...^.^...^.^...
   ...............
   ..^...^.....^..
   ...............
   .^.^.^.^.^...^.
   ...............
*)
let example_input =
  {|.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............|}
;;

include Day_test.Make (struct
    module Day = Aoc2025.Day07

    let part1 : Day.t1 Day_test.part_spec =
      {
        testable = Alcotest.int
      ; examples = [ (example_input, 21) ]
      ; constraints = Some [ LESS_THAN 1703; LESS_THAN 1660 ]
      ; personal = Some 1_600
      }
    ;;

    let part2 : Day.t2 Day_test.part_spec =
      {
        testable = Alcotest.int
      ; examples = [ (example_input, 40) ]
      ; constraints = None
      ; personal = Some 8_632_253_783_011
      }
    ;;

    let additional_tests = None
  end)
